name: Deploy

on:
  push:
    branches:
      - main # или master — какая у тебя ветка?

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

            cd ~/Znaniya.KIPO
            git stash
            git pull origin main

            # Backend
            cd ~/Znaniya.KIPO/backend
            npm install
            npm run build
            pm2 restart backend

            # Frontend
            cd ~/Znaniya.KIPO/frontend
            npm install
            npm run build
            pm2 restart frontend

            echo "✅ Deploy done!"
